var sponsors =
[   { sponsor_name: 'AJi Software',
    url: 'http://ajisoftware.com',
},
  { sponsor_name: 'Adaptive Solutions Group',
    url: 'http://www.adaptivesg.com',
},
  { sponsor_name: 'Advantage Tech',
    url: 'http://www.advantagetech.net',
},
  { sponsor_name: 'AdventureTech',
    url: 'http://www.atgsoftware.com',
},
  { sponsor_name: 'Balance Innovations',
    url: 'http://balanceinnovations.com',
},
  { sponsor_name: 'Bradford and Galt',
    url: 'http://bradfordandgalt.com',
},
  { sponsor_name: 'CODE Magazine',
    url: 'http://www.codemag.com',
},
  { sponsor_name: 'Centriq Training',
    url: 'http://www.centriq.com',
},
  { sponsor_name: 'Cerner',
    url: 'http://engineering.cerner.com/',
},
  { sponsor_name: 'ComponentOne',
    url: 'http://www.componentone.com',
},
  { sponsor_name: 'DSI',
    url: 'http://www.dsiglobal.com',
},
  { sponsor_name: 'DST',
    url: 'http://www.dstsystems.com',
},
  { sponsor_name: 'DevExpress',
    url: 'http://devexpress.com',
},
  { sponsor_name: 'Dice',
    url: 'http://www.dice.com/hackathon',
},
  { sponsor_name: 'Epiq Systems',
    url: 'http://epiqsystems.com',
},
  { sponsor_name: 'Freightquote',
    url: 'http://freightquote.com',
},
  { sponsor_name: 'Garmin',
    url: 'http://www.garmin.com',
},
  { sponsor_name: 'Jack Henry And Associates',
    url: 'https://www.jackhenry.com',
},
  { sponsor_name: 'JetBrains',
    url: 'http://www.jetbrains.com',
},
  { sponsor_name: 'KCNext',
    url: 'http://kcnext.com',
},
  { sponsor_name: 'KU Edwards Campus',
    url: 'http://edwardscampus.ku.edu',
},
  { sponsor_name: 'Kauffman Labs',
    url: 'http://kauffmanlabs.org',
},
  { sponsor_name: 'Keyhole Software',
    url: 'http://keyholesoftware.com',
},
  { sponsor_name: 'LRS Consulting Services',
    url: 'http://www.lrs.com/consulting',
},
  { sponsor_name: 'Microsoft',
    url: 'http://www.microsoft.com',
},
  { sponsor_name: 'Multi Service',
    url: 'http://www.multiservicecareers.com',
},
  { sponsor_name: 'Netchemia',
    url: 'http://www.netchemia.com',
},
  { sponsor_name: 'OReilly',
    url: 'http://www.oreilly.com',
},
  { sponsor_name: 'Oakwood Systems',
    url: 'http://www.oakwoodsys.com',
},
  { sponsor_name: 'Paige Technologies',
    url: 'http://paigetech.com',
},
  { sponsor_name: 'Perceptive Software',
    url: 'http://www.perceptivesoftware.com',
},
  { sponsor_name: 'Pluralsight',
    url: 'http://pluralsight.com',
},
  { sponsor_name: 'Sprint',
    url: 'http://www.sprint.com',
},
  { sponsor_name: 'Stackify',
    url: 'http://www.stackify.com',
},
  { sponsor_name: 'TEKSystems',
    url: 'http://www.teksystems.com',
},
  { sponsor_name: 'Triple I Consulting',
    url: 'http://www.triplei.com',
},
  { sponsor_name: 'Twilio',
    url: 'https://www.twilio.com',
},
  { sponsor_name: 'UnitedLex',
    url: 'http://unitedlex.com',
},
  { sponsor_name: 'Valorem',
    url: 'http://kcdc.valoremconsulting.com',
}
]
;